sudo: false
language: python
python:
 - '3.5'
install:
  - pip install -U tox
  - mkdir -p ~/.local/bin; curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C ~/.local/bin
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py

env:
  global:
    - TS=$TESTSPACE_TOKEN/${TRAVIS_BRANCH}
    - NAME=travis.Build.${TRAVIS_BUILD_NUMBER}
    - secure: FlN3oS2RQ+Hi4LGx4XvcHl4azyGfc7QoylT82qzFzPRKI6a+1zSxoLxTD3o9lZwAPqvEd5bBCO6+LntB5a7d0Nqg6T5/ThhgbSZjXYbgYqcFMYU/HRHVce+5z+nmXzZZVgbrw9Ydxf1Qqfnk6GdR+Ytwnwm+sVt73A7y2ohVRuM9QIpWm9fLE2xdZ0gZv8BOKJO+sDmVmQHYKQsMBwzg1ZC3A35pyZwcD8DWmFe/Y62LR6NLFmxibOH2JbNa/sWDtRaZiDaxWMhW/Vxz8U55NiySyDehjXsOsU8HJmkkBfYMYv6g6dsMauJldPvA27UCfndUyhIYo7w9ehMS2NGpvMFg9d9vqPNVPE+ZPcrXaqSh55hPBBDNUgM2oMzA7wPTGhCPZxnytVf37JQa7KV+sdC57JxEfMz3iMY760MimpmYChKJfAV4iY75n5Zdj+c7FYhXgUSQWOqaTT1YasgND9k3nxOJDLd0MjXhyYKSZu5LnEDgi3QqYg5C93oiPhSfNUFhKZ4GvDjoL6kOT2Dk1yCGE5ba+SjkCWNSqA+hRyUZC5+E30GXT6v/Ch6jT+aBNnNZXk1j6TPuXv3GFnrUEP0ZH+II+iXjjeop9cnWb7ZBl40ncE5KUWIVWuW2EWVarESmKrkqdmxjgAA/fshWNIG1YOxl80OYkmjcX2bkniU=

  matrix:
    - TESTENV=coveralls RESULTS="[$TESTENV]results.xml [$TESTENV]coverage.xml"
    - TESTENV=linting RESULTS=analysis.log{lint}
    - TESTENV=py26 RESULTS=[$TESTENV]results.xml
    - TESTENV=py27 RESULTS=[$TESTENV]results.xml
    - TESTENV=py33 RESULTS=[$TESTENV]results.xml
    - TESTENV=py34 RESULTS=[$TESTENV]results.xml
    - TESTENV=py35 RESULTS=[$TESTENV]results.xml
    - TESTENV=pypy RESULTS=[$TESTENV]results.xml
    - TESTENV=py27-pexpect RESULTS=[$TESTENV]results.xml
    - TESTENV=py27-xdist RESULTS=[$TESTENV]results.xml
    - TESTENV=py27-trial RESULTS=[$TESTENV]results.xml
    - TESTENV=py35-pexpect RESULTS=[$TESTENV]results.xml
    - TESTENV=py35-xdist RESULTS=[$TESTENV]results.xml
    - TESTENV=py35-trial RESULTS=[$TESTENV]results.xml
    - TESTENV=py27-nobyte RESULTS=[$TESTENV]results.xml
    - TESTENV=doctesting RESULTS=[$TESTENV]results.xml
    - TESTENV=freeze
    - TESTENV=docs
matrix:
  include:
    - env: TESTENV=py36 RESULTS=[$TESTENV-3.6-dev]results.xml
      python: 3.6-dev
    - env: TESTENV=py37 RESULTS=[$TESTENV-3.6-dev]results.xml
      python: nightly
script:
  - tox --recreate -e $TESTENV
  - testspace $RESULTS $TS?add#$NAME || testspace $RESULTS $TS?start#$NAME
after_script:
  - python travis_after_all.py https://api.travis-ci.org
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        testspace $TESTSPACE_TOKEN/${TRAVIS_BRANCH}?finish#travis.Build.${TRAVIS_BUILD_NUMBER}
      fi
