sudo: false
language: python
python:
  - '3.5'
  
install:
  - pip install -U tox
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com

env:
  global:
    - RESULTS=results.xml{testing}
 
  matrix:
  #  - TESTENV=coveralls RESULTS="[$TESTENV]results.xml{testing} [$TESTENV]coverage.xml"
     - TESTENV=linting RESULTS=analysis.log{lint} #rst-output.txt
     - TESTENV=py26 
     - TESTENV=py27 
  #  - TESTENV=py33 RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=py34 RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=py35 RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=pypy RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=py27-pexpect RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=py27-xdist RESULTS=[$TESTENV]results.xml{testing}
     - TESTENV=py27-trial 
  #  - TESTENV=py35-pexpect RESULTS=[$TESTENV]results.xml{testing}
  #  - TESTENV=py35-xdist RESULTS=[$TESTENV]results.xml{testing}
     - TESTENV=py35-trial 
  #  - TESTENV=py27-nobyte RESULTS=[$TESTENV]results.xml{testing}
     - TESTENV=doctesting RESULTS=doc/results*.xml
  #  - TESTENV=freeze
  #  - TESTENV=docs 

#matrix:
#  include:
#    - env: TESTENV=py36 RESULTS=[$TESTENV]results.xml
#      python: 3.6-dev
#    - env: TESTENV=py37 RESULTS=[$TESTENV]results.xml
#      python: nightly


script:
  - tox --recreate -e $TESTENV
  - testspace [$TESTENV]$RESULTS 
